### ISSUE TITLE
wsl2子系统报错Could not resolve host: github.

### ISSUE THREAD

**Issue by zxcvbnm3057** [dotnetcore/FastGithub#103]
如题

**Comment by westfly** [comment]
我在wsl1下用window版本的fastgithubui是可以的。
只是下载github的文件需要设置环境变量
```shell
export CURL_CA_BUNDLE=/etc/ssl/certs/fastgithub.cer
```

**Comment by sczh01** [comment]
I also encounter this issue at WSL2. 
Anyone has the solution at WSL2 now?

My config:
Host: Windows 10/19043.1526, Linux of WSL2: ubuntu18.04

**Comment by sczh01** [comment]
附上详细步骤和 Log
--------------------------------------------------------------------------------------------
tony@PC1X5GLS:~/fastgithub_linux-x64$ sudo ./fastgithub 
[sudo] password for tony: 
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
2022-04-20T16:44:52.6787409+08:00 [INF]
FastGithub.HttpServer.CaCertInstallerOfLinuxDebian
已自动向系统安装CA证书cacert/fastgithub.crt

2022-04-20T16:44:52.9176289+08:00 [INF]
FastGithub.HttpServer
已监听http://localhost:38457，http代理服务启动完成

2022-04-20T16:44:53.0647607+08:00 [INF]
FastGithub.AppHostedService
FastGithub启动完成，当前版本为v2.1.4，访问 https://github.com/dotnetcore/fastgithub 关注新版本

2022-04-20T16:44:54.0806799+08:00 [WRN]
FastGithub.AppHostedService
请设置系统自动代理为http://127.0.0.1:38457，或手动代理http/https为127.0.0.1:38457

[2022-04-20 16:46:08] [FATAL] Get "https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022-04-20T16:46:50.3727702+08:00 [ERR]
FastGithub.HttpServer.RequestLoggingMiddleware
GET https://github.com/xxxx/Voron-2.git/info/refs responded 502 in 8349.2928 ms
System.Net.Http.HttpRequestException: 找不到任何可成功连接的IP (github.com:443)
 ---> System.AggregateException: 找不到任何可成功连接的IP
   at FastGithub.Http.HttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   at FastGithub.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at FastGithub.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)

**Comment by EzrealJ** [comment]
你好，这种情况在刚启动时较为常见，因为FastGithub需要一段时间“学习”和“探索”可以加速的链路；这种情况一般在多次访问后得到改善，但极端情况下（例如当地网络彻底封锁了目标地址）；多次访问也无法得到改善。

**Comment by ns-cn** [comment]
> 

我在MacOS上全天运行，但GitHub时好时坏，就会出现【找不到任何可成功连接的IP】

**Comment by zxcvbnm3057** [comment]
给后来者：

在wsl2子系统里面重新安装linux版本的fastGitHub然后设置子系统使用自己的代理而不是宿主代理可以解决此问题

**Comment by ns-cn** [comment]
> 

请教一下， 那MacOS遇到这个问题怎么解决呢？

**Comment by zxcvbnm3057** [comment]
熬了个通宵实现了一种更方便的办法，pr #280 

也可以去我的fork里下载或者拉代码本地编译
