### ISSUE TITLE
The hostname could not be parsed

### ISSUE THREAD

**Issue by hblifeng** [dotnetcore/FastGithub#114]
之前在电脑上用过很长一段时间fastgithub，能够正常运行，最近运行发现出现如下问题

**Bug描述**
2022-01-24T17:50:21.3428850+08:00 [ERR]
Microsoft.Extensions.Hosting.Internal.Host
BackgroundService failed
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at System.Net.Http.MacProxy.GetProxy(Uri )
   at FastGithub.AppHostedService.UseFastGithubProxyAsync()
   at FastGithub.AppHostedService.CheckFastGithubProxyAsync(CancellationToken cancellationToken)
   at FastGithub.AppHostedService.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService )

2022-01-24T17:50:21.3707950+08:00 [FTL]
Microsoft.Extensions.Hosting.Internal.Host
The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at System.Net.Http.MacProxy.GetProxy(Uri )
   at FastGithub.AppHostedService.UseFastGithubProxyAsync()
   at FastGithub.AppHostedService.CheckFastGithubProxyAsync(CancellationToken cancellationToken)
   at FastGithub.AppHostedService.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService )

**软件信息**
 - 操作系统:  macos 12.1
 - FastGithub： v2.0.6
[log20220124.txt](https://github.com/dotnetcore/FastGithub/files/7924530/log20220124.txt)

**Comment by zhweiGuo** [comment]
遇到了同样的问题，mac 11.6。我是用了一下午就出问题了。

**Comment by xljiulang** [comment]
已修复，see https://github.com/dotnetcore/FastGithub/commit/519c4d8e8045f2028cbe02081b4fff95100766d3

**Comment by xljiulang** [comment]
更新到2.1.4解决。
