### ISSUE TITLE
Ubuntu x86_64 无法启动 Unhandled exception. System.IO.IOException: The configured user limit (256) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.

### ISSUE THREAD

**Issue by Ljzd-PRO** [dotnetcore/FastGithub#161]
**Bug描述**
```
Unhandled exception. System.IO.IOException: The configured user limit (256) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean )
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String )
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String )
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 , Action`1 , TState )
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 , Action )
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder )
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at FastGithub.Program.Main(String[] args)
已放弃
```
如果是兼容性问题的话，是否可以自己编译

**重现步骤**
1.
```
sudo ./fastgithub
```
 

**软件信息**
 - 操作系统: Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-41-generic x86_64)
 - FastGithub： v2.1.4

**Comment by imwcc** [comment]
有问题
