### ISSUE TITLE
m1 mac运行程序失败报错

### ISSUE THREAD

**Issue by zhang0227** [dotnetcore/FastGithub#179]
**Bug描述**
./fastgithub后出现报错
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The access code is invalid.
 (0x8007000C)
File name: 'Microsoft.AspNetCore.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at FastGithub.Program.CreateHostBuilder(String[] args)
   at FastGithub.Program.Main(String[] args)
zsh: abort      ./fastgithub

**软件信息**
 - 操作系统: mac oc Monterey 12.3.1 ,m1 芯片
 - FastGithub： v2.1.4

**Comment by mario-shang** [comment]
你是用的arm64的包吗？ [fastgithub_osx-arm64.zip](https://github.com/dotnetcore/FastGithub/releases/download/2.1.4/fastgithub_osx-arm64.zip)

**Comment by EzrealJ** [comment]
请使用x64的包
