### ISSUE TITLE
无法正常使用（一台正常，一台有问题）

### ISSUE THREAD

**Issue by ISuuuu** [dotnetcore/FastGithub#206]
**Bug描述** 
两台电脑都是win11 系统，其中一台打开后日志报错，另一台正常

![image](https://user-images.githubusercontent.com/16700132/190541010-6f1594ed-4beb-4a0c-b319-eaffd89c8cc1.png)
log日志中显示：
--------------------------------------------------------------------------------------------------------------------------------
2022-09-16T10:07:47.5533189+08:00 [ERR]
Microsoft.Extensions.Hosting.Internal.Host
BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at FastGithub.AppHostedService.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService )
2022-09-16T10:07:47.5781429+08:00 [FTL]
Microsoft.Extensions.Hosting.Internal.Host
The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at FastGithub.AppHostedService.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService )
-------------------------------------------------------------------------------------------------------------------------------- 
 

**软件信息**
 - 操作系统: [e.g. win11 x64]
 - FastGithub： [e.g.  v2.1.4]

**Comment by ISuuuu** [comment]
就最近几天出的问题，之前一切正常。

**Comment by lucktu** [comment]
configure this to Ignore
