### ISSUE TITLE
无法连接到github.com:443

### ISSUE THREAD

**Issue by vblegend** [dotnetcore/FastGithub#214]
**Bug描述**
2022-10-11T19:58:10.4936646+08:00 [ERR]
Microsoft.AspNetCore.Server.Kestrel
Connection id "0HMLBFUDSULLM", Request id "0HMLBFUDSULLM:00000002": An unhandled exception was thrown by the application.
System.AggregateException: 无法连接到github.com:443 (Resource temporarily unavailable)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 )
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken )
   at FastGithub.HttpServer.HttpProxyMiddleware.CreateConnectionAsync(HostString host, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at FastGithub.HttpServer.HttpProxyMiddleware.CreateConnectionAsync(HostString host, CancellationToken cancellationToken)
   at FastGithub.HttpServer.HttpProxyMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

2022-10-11T19:58:10.4952411+08:00 [INF]
Microsoft.AspNetCore.Hosting.Diagnostics
 
**重现步骤**
git pull origin xxxx

**软件信息**
 - Debian11  WSL2 
 - FastGithub： [e.g.  v2.1.4]

**Comment by vblegend** [comment]
抱歉  我的问题   dnscrypt-proxy 目录没给到权限造成的
