### ISSUE TITLE
自定义域名可造成转发死循环

### ISSUE THREAD

**Issue by WeihanLi** [dotnetcore/FastGithub#27]
自定义配置信息：

``` json
{
  "FastGithub": {
    "DomainConfigs": {
      "fastgithub.local": {
        "TlsIgnoreNameMismatch": true,
        "IPAddress": "127.0.0.1"
      }
    }
  }
}
```

访问 `https://fastgithub.local` 的时候一直报错，从 EventLog 里找到的错误信息如下：

```
Category: FastGithub.ReverseProxy.RequestLoggingMilldeware
EventId: 0
SpanId: bd4f40a0c13cbf4e
TraceId: f4a634f8bb834f4eacff58dfee75a9a1
ParentId: 0000000000000000
ConnectionId: 0HMATJ2EDS06N
RequestId: 0HMATJ2EDS06N:00000002
RequestPath: /

GET https://fastgithub.local/ responded 502 in 76838.6546 ms
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at FastGithub.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\projects\sources\FastGithub\FastGithub.Http\HttpClientHandler.cs:line 81
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)

```

**Comment by xljiulang** [comment]
ip不能指向本机 会造成请求死循环

**Comment by WeihanLi** [comment]
感觉可能可以实现一个简单的请求死循环的机制，
如果出现了死循环可以 fallback 到一个默认的响应，没有默认的响应就返回 404/502...

**Comment by xljiulang** [comment]
是的，可以在httpclient handler里面判断请求目标的最终ip和端口，如果是fagithub本身，且请求源是本身的时候，直接中断。这个需要修改fastgithub转发的请求信息，加入标记
