### ISSUE TITLE
启动时报错: dns拦截器和tcp拦截器异常

### ISSUE THREAD

**Issue by AkagawaTsurunaki** [dotnetcore/FastGithub#278]
**Bug描述**
2023-05-04T18:43:51.0019880+08:00 [INF]
FastGithub.HttpServer
已监听[https://localhost:443](https://localhost/)，https反向代理服务启动完成

2023-05-04T18:43:51.0769982+08:00 [INF]
FastGithub.HttpServer
已监听http://localhost:81/，http反向代理服务启动完成

2023-05-04T18:43:51.0793362+08:00 [INF]
FastGithub.HttpServer
已监听ssh://localhost:22，github的ssh反向代理服务启动完成

2023-05-04T18:43:51.0804415+08:00 [INF]
FastGithub.HttpServer
已监听git://localhost:9418，github的git反向代理服务启动完成

2023-05-04T18:43:51.1408088+08:00 [INF]
FastGithub.AppHostedService
FastGithub启动完成，当前版本为v2.1.4，访问 https://github.com/dotnetcore/fastgithub 关注新版本

2023-05-04T18:43:51.6972500+08:00 [ERR]
FastGithub.PacketIntercept.DnsInterceptHostedService
dns拦截器异常
System.ComponentModel.Win32Exception (1058): 无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。
   at FastGithub.PacketIntercept.Dns.DnsInterceptor.InterceptAsync(CancellationToken cancellationToken)
   at FastGithub.PacketIntercept.DnsInterceptHostedService.ExecuteAsync(CancellationToken stoppingToken)

2023-05-04T18:43:51.6973343+08:00 [ERR]
FastGithub.PacketIntercept.TcpInterceptHostedService
tcp拦截器异常
System.ComponentModel.Win32Exception (1058): 无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。
   at FastGithub.PacketIntercept.Tcp.TcpInterceptor.InterceptAsync(CancellationToken cancellationToken)
   at FastGithub.PacketIntercept.TcpInterceptHostedService.ExecuteAsync(CancellationToken stoppingToken)

**重现步骤**
1.  以管理员模式运行FastGithub
 

**软件信息**
 - 操作系统: [win10-x64]
 - FastGithub： [v2.1.4]

**Comment by 2399404606** [comment]
解决了吗？ 求解决方案
