### ISSUE TITLE
服务启动不了，提示dns拦截器异常

### ISSUE THREAD

**Issue by landonzeng** [dotnetcore/FastGithub#287]
**Bug描述**
Bug的详细描述内容

服务启动不了，提示dns拦截器异常：
FastGithub.PacketIntercept.DnsInterceptHostedService
dns拦截器异常
System.ComponentModel.Win32Exception (0x80320007): 子层不存在。
   at FastGithub.PacketIntercept.Dns.DnsInterceptor.InterceptAsync(CancellationToken cancellationToken)
   at FastGithub.PacketIntercept.DnsInterceptHostedService.ExecuteAsync(CancellationToken stoppingToken)

**重现步骤**
1.  双击运行FastGithub.UI.exe程序
2.  日志提示dns拦截异常
![image](https://github.com/dotnetcore/FastGithub/assets/7336781/68e553fa-4e84-451e-b006-122f710246c7)
4.  查看log日志，提示如下
![image](https://github.com/dotnetcore/FastGithub/assets/7336781/14850393-2f9f-4d7e-9ae7-c540f257a8bb)

 

**软件信息**
 - 操作系统:  win10-x64
 - FastGithub： v2.1.4

**Comment by 2399404606** [comment]
解决了吗？ 求解决方案
