### ISSUE TITLE
对git客户端有效吗

### ISSUE THREAD

**Issue by liaoxuewei** [dotnetcore/FastGithub#44]
这个对git客户端有效吗？好像我启动了以后，git客户端下载不了源码！？

**Comment by liaoxuewei** [comment]
git.exe clone --progress -v "https://github.com/dotnetcore/FastGithub.git" "E:\Opensource\FastGithub"
Cloning into 'E:\Opensource\FastGithub'...
fatal: unable to access 'https://github.com/dotnetcore/FastGithub.git/': The requested URL returned error: 502


git did not exit cleanly (exit code 128) (1154 ms @ 30/08/2021 09:29:11)

我以前下载只是不稳定，但是现在好像多次尝试都失败了！

**Comment by xljiulang** [comment]
你浏览器能访问的话，git.exe的https请求也是完全可以的。

**Comment by liaoxuewei** [comment]
git客户端访问github时，看到控制台出现下面的错误信息了：
fail: FastGithub.ReverseProxy.RequestLoggingMiddleware[0]
      GET https://github.com/dotnetcore/FastGithub.git/info/refs responded 502 in 1029.987 ms
      System.Net.Http.HttpRequestException: Authentication failed, see inner exception. (140.82.121.4:443)
       ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> System.ComponentModel.Win32Exception (0x80090302): 不支援要求的功能
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at FastGithub.Http.HttpClientHandler.<CreateSocketsHttpHandler>b__6_0(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at FastGithub.Http.HttpClientHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at FastGithub.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig,

**Comment by liaoxuewei** [comment]
试了重启好几次，还是一样的结果，浏览器正常使用，但是git客户端一直都是这个异常

**Comment by xljiulang** [comment]
猜测你的系统是可能是win7，在win7年代，系统默认最高ssl版本是tls1.0 ，如今tls1.0和tls1.1都已经被历史所淘汰了，tls1.2和tls1.3才受支持。FastGithub使用系统支持的 tls，你可以查找win7开启tls1.2的相关文章。

**Comment by liaoxuewei** [comment]
1.用着用着访问github就出现这个图了：
![1630291140(1)](https://user-images.githubusercontent.com/970765/131277673-82452fe6-9aea-4ddd-86c1-f54e31fb1c57.png)

2.然后再强制进去访问github就出现：
{
"error": "Request",
"message": "Authentication failed, see inner exception. (52.78.231.108:443)"
}
{
error: "Request",
message: "Authentication failed, see inner exception. (52.78.231.108:443)"
}

我找文章试试win7开启tls1.2试试先，上面信息先留底，试完再看看

**Comment by liaoxuewei** [comment]
参考https://blog.csdn.net/xingyuhailing/article/details/73320989文章开启tls1.2，好像可以用git客户端了！我再观察是否还会出现上一层楼的问题

**Comment by liaoxuewei** [comment]
> 猜测你的系统是可能是win7，在win7年代，系统默认最高ssl版本是tls1.0 ，如今tls1.0和tls1.1都已经被历史所淘汰了，tls1.2和tls1.3才受支持。FastGithub使用系统支持的 tls，你可以查找win7开启tls1.2的相关文章。

非常感谢啊，之前没有了解过这些东西，我好一段时间好像使用tls的东西都有问题，估计都跟这个有关了，因为对自己影响不大，当时没有怎么在意！

**Comment by liaoxuewei** [comment]
另外，没有深入了解这个软件的原理，我想问问，是不是可以用这个用来做类似翻墙，如果可以不是很好？

**Comment by xljiulang** [comment]
这个不是翻墙软件，也不做了这个功能。

**Comment by liaoxuewei** [comment]
> 另外，没有深入了解这个软件的原理，我想问问，是不是可以用这个用来做类似翻墙，如果可以不是很好？

注：我使用chrome为主，有一些代理工具来翻墙，主要是为了查找技术文章，但是都不是很好用或者不稳定，这个原理是什么？哪里有介绍吗？

**Comment by xljiulang** [comment]
无法提供。

**Comment by liaoxuewei** [comment]
好吧，哈哈，自己看看吧

**Comment by liaoxuewei** [comment]
这个问题还是存在哦。。。

用着用着控制台就出现：
info: FastGithub.DomainResolve.DomainResolver[0]
      [github.com->140.82.121.4]
fail: FastGithub.ReverseProxy.RequestLoggingMiddleware[0]
      GET https://github.com/_alive responded 502 in 961.3459 ms
      System.Net.Http.HttpRequestException: Authentication failed, see inner exception. (140.82.121.4:443)
       ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的訊息超出預期或格式不正確。
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at FastGithub.Http.HttpClientHandler.<CreateSocketsHttpHandler>b__6_0(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at FastGithub.Http.HttpClientHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at FastGithub.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig,
HttpTransformer transformer)

然后访问github出现：
{
"error": "Request",
"message": "Authentication failed, see inner exception. (140.82.121.4:443)"
}
{
error: "Request",
message: "Authentication failed, see inner exception. (140.82.121.4:443)"
}

**Comment by liaoxuewei** [comment]
重新启动又好像可以了，但是出问题有点快，就半个小时不到就出现了

**Comment by xljiulang** [comment]
那你加群，然后群里联系我，我想看看你系统实际情况
