### ISSUE TITLE
启动异常

### ISSUE THREAD

**Issue by FatuityCookie** [dotnetcore/FastGithub#87]
**Bug描述**
2021-11-12T13:53:04.4626685+08:00 [ERR]
FastGithub.PacketIntercept.DnsInterceptHostedService
dns拦截器异常
System.ComponentModel.Win32Exception (0x80320009): 具有该 GUID 或 LUID 的对象已经存在。
   at FastGithub.PacketIntercept.Dns.DnsInterceptor.InterceptAsync(CancellationToken cancellationToken)
   at FastGithub.PacketIntercept.DnsInterceptHostedService.ExecuteAsync(CancellationToken stoppingToken)

2021-11-12T13:53:04.4629053+08:00 [ERR]
FastGithub.PacketIntercept.TcpInterceptHostedService
tcp拦截器异常
System.ComponentModel.Win32Exception (0x80320009): 具有该 GUID 或 LUID 的对象已经存在。
   at FastGithub.PacketIntercept.Tcp.TcpInterceptor.InterceptAsync(CancellationToken cancellationToken)
   at FastGithub.PacketIntercept.TcpInterceptHostedService.ExecuteAsync(CancellationToken stoppingToken)

**重现步骤**
 管理员运行首次启动

**软件信息**
 - 操作系统: [e.g. win11-x64]
 - FastGithub： [e.g.  v2.0.7]

**Comment by xljiulang** [comment]
首次启动时，驱动在一些系统遇到这个已知问题。

**Comment by Youngson** [comment]
我这里是在win7系统上启动时会报错，窗口可以正常打开，但是流量、日志标签页没有任何信息。
“无法启动此程序，因为计算机中丢失api-ms-win-core-winrt-l1-1-0.dll”
.net安装的版本是4.8，c++库2005、2008、2010、2012、2013、2015-2022都有，不知道还缺什么库。但是在win10中一切正常。

**Comment by xljiulang** [comment]
@xljiulang v2.x需要win10或以上
